/**
 * AI-graded English assessment analysis.
 *
 * Given a candidate's answers, computes a per-skill breakdown, picks a CEFR level,
 * generates a personalised study plan + course recommendation, and renders a radar
 * chart SVG of the four English competencies.
 *
 * If ANTHROPIC_API_KEY is set, the narrative analysis is generated by Claude.
 * Otherwise a deterministic template fills in. Either way, the chart + scores
 * are computed locally so the email always has consistent data.
 */

export type SkillTag = 'grammar' | 'vocab' | 'reading' | 'listening';

export type AnsweredQuestion = {
  questionId: string;
  selectedIndex: number;
  correct: boolean;
  skillTag?: string | null;
  difficulty?: number | null;
};

export type SkillScore = {
  skill: SkillTag;
  correct: number;
  total: number;
  pct: number; // 0–100
};

export type AnalysisInput = {
  name: string;
  email: string;
  locale: 'ar' | 'en';
  level: string; // A1..C2
  score: number;
  total: number;
  answers: AnsweredQuestion[];
};

export type AnalysisOutput = {
  level: string;
  score: number;
  total: number;
  skills: SkillScore[];
  // Narrative pieces — used in email
  summary: string;
  competencies: { skill: SkillTag; label: string; analysis: string; recommendation: string }[];
  recommendedCourse: { id: string; title: string; why: string };
  studyPlan: { week: string; focus: string; activities: string[] }[];
  /** SVG markup of a 4-axis radar chart with the candidate's scores. */
  radarSvg: string;
};

/* ============================================================================
   Skill score computation
   ============================================================================ */

const SKILL_LABEL: Record<SkillTag, { en: string; ar: string }> = {
  grammar:   { en: 'Grammar',   ar: 'القواعد' },
  vocab:     { en: 'Vocabulary', ar: 'المفردات' },
  reading:   { en: 'Reading',   ar: 'القراءة' },
  listening: { en: 'Listening', ar: 'الاستماع' },
};

const SKILLS: SkillTag[] = ['grammar', 'vocab', 'reading', 'listening'];

export function computeSkillScores(answers: AnsweredQuestion[]): SkillScore[] {
  return SKILLS.map((skill) => {
    const rows = answers.filter((a) => (a.skillTag ?? 'grammar') === skill);
    const correct = rows.filter((a) => a.correct).length;
    const total = rows.length;
    return {
      skill,
      correct,
      total,
      pct: total === 0 ? 0 : Math.round((correct / total) * 100),
    };
  });
}

/* ============================================================================
   Radar chart SVG
   ============================================================================ */

export function radarChartSvg(skills: SkillScore[], locale: 'ar' | 'en' = 'en'): string {
  const W = 560;
  const H = 460;
  const cx = W / 2;
  const cy = H / 2 + 10;
  const r = 150;
  const axes = SKILLS.length;
  // 4 axes: 0=top, 1=right, 2=bottom, 3=left
  const angle = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / axes;

  function point(idx: number, value01: number) {
    const rr = r * Math.max(0.04, value01);
    const a = angle(idx);
    return { x: cx + Math.cos(a) * rr, y: cy + Math.sin(a) * rr };
  }

  const grid = [0.25, 0.5, 0.75, 1].map((p) => {
    const pts = SKILLS.map((_, i) => point(i, p));
    return `<polygon points="${pts.map((pt) => `${pt.x.toFixed(1)},${pt.y.toFixed(1)}`).join(' ')}" fill="none" stroke="rgba(15,27,29,0.12)" stroke-width="1"/>`;
  }).join('');

  const axisLines = SKILLS.map((_, i) => {
    const end = point(i, 1);
    return `<line x1="${cx}" y1="${cy}" x2="${end.x.toFixed(1)}" y2="${end.y.toFixed(1)}" stroke="rgba(15,27,29,0.12)" stroke-width="1"/>`;
  }).join('');

  const labels = SKILLS.map((sk, i) => {
    const p = point(i, 1.18);
    return `<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" font-family="Georgia,'Times New Roman',serif" font-size="14" font-weight="600" fill="#0E5132" text-anchor="middle" dominant-baseline="middle">${SKILL_LABEL[sk][locale]}</text>`;
  }).join('');

  const valuePts = skills.map((s, i) => point(i, s.pct / 100));
  const valuePolygon = `<polygon points="${valuePts.map((pt) => `${pt.x.toFixed(1)},${pt.y.toFixed(1)}`).join(' ')}" fill="rgba(201,162,74,0.28)" stroke="#C9A24A" stroke-width="2.5"/>`;
  const valueDots = valuePts
    .map((pt) => `<circle cx="${pt.x.toFixed(1)}" cy="${pt.y.toFixed(1)}" r="4.5" fill="#0E5132" stroke="#C9A24A" stroke-width="1.5"/>`)
    .join('');

  const pctLabels = skills
    .map((s, i) => {
      const p = point(i, Math.max(0.18, s.pct / 100 + 0.06));
      return `<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" font-family="Georgia,serif" font-size="11" fill="#0F1B1D" text-anchor="middle" dominant-baseline="middle">${s.pct}%</text>`;
    })
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <rect width="100%" height="100%" fill="#FBF8F2"/>
  ${grid}
  ${axisLines}
  ${valuePolygon}
  ${valueDots}
  ${labels}
  ${pctLabels}
</svg>`;
}

/* ============================================================================
   Course recommendation (deterministic, level + skill aware)
   ============================================================================ */

function recommendCourse(level: string, skills: SkillScore[]): AnalysisOutput['recommendedCourse'] {
  const weak = [...skills].sort((a, b) => a.pct - b.pct)[0];
  if (level === 'A1' || level === 'A2') {
    return {
      id: 'adults',
      title: 'Adult Conversation (Foundation track)',
      why: `At ${level}, the priority is building a confident foundation in everyday English. Our small-group Foundation track focuses on the four skills together, with extra ${weak.skill} work where needed.`,
    };
  }
  if (level === 'B1' || level === 'B2') {
    if (weak.skill === 'reading' || weak.skill === 'grammar') {
      return {
        id: 'exams',
        title: 'TOEFL & IELTS Prep',
        why: `At ${level}, you have the range to start exam prep. Our TOEFL/IELTS track will sharpen your ${weak.skill} (your current weakest area) while you build the test-taking strategies that turn intermediate English into a band 6.5+ or TOEFL 80+.`,
      };
    }
    return {
      id: 'business',
      title: 'Business English',
      why: `At ${level} you are ready for workplace English. The Business track focuses on professional speaking, writing, and presentations — using your strengths to fast-track confident communication.`,
    };
  }
  // C1/C2
  return {
    id: 'private',
    title: 'Private 1-on-1 (Advanced)',
    why: `At ${level}, group classes won't stretch you. A dedicated tutor will target the specific edges of your English — nuance, register, idiom — and prepare you for the demands of native-level work.`,
  };
}

/* ============================================================================
   Study plan
   ============================================================================ */

function buildStudyPlan(level: string, skills: SkillScore[]): AnalysisOutput['studyPlan'] {
  const weak = [...skills].sort((a, b) => a.pct - b.pct);
  const w1 = weak[0]?.skill ?? 'grammar';
  const w2 = weak[1]?.skill ?? 'vocab';

  return [
    {
      week: 'Weeks 1–2 · Diagnostic & Foundation',
      focus: `Stabilise your ${SKILL_LABEL[w1].en} as your priority skill`,
      activities: [
        `30 min/day targeted ${SKILL_LABEL[w1].en} drills`,
        '15 min/day listening (BBC Learning English or VOA Learning English)',
        'Weekly 1-hour conversation circle at Rai',
      ],
    },
    {
      week: 'Weeks 3–6 · Range',
      focus: `Add depth in ${SKILL_LABEL[w2].en} while consolidating week 1–2 gains`,
      activities: [
        'Read one news article per day (Reuters, Al Jazeera English)',
        'Write a short journal entry (5 sentences) every other day',
        'Bi-weekly mock test at Rai with feedback',
      ],
    },
    {
      week: 'Weeks 7–10 · Speaking & Confidence',
      focus: 'Convert understanding into spoken fluency',
      activities: [
        'Two conversation sessions per week (group or 1-on-1)',
        'Watch one English film with English subtitles each week',
        'Record yourself summarising an article for 1 minute',
      ],
    },
    {
      week: 'Weeks 11–12 · Reassessment',
      focus: 'Re-take the assessment and target the next level up',
      activities: [
        'Full mock exam at Rai',
        'Set goals for the next 3 months with your Rai instructor',
        'Decide on follow-on course (exam prep, business, or private)',
      ],
    },
  ];
}

/* ============================================================================
   Narrative analysis — DeepSeek (OpenAI-compatible) w/ template fallback
   ============================================================================ */

function templateNarrative(input: AnalysisInput, skills: SkillScore[]) {
  const level = input.level;
  const overall = Math.round((input.score / Math.max(1, input.total)) * 100);
  const summary = `${input.name} scored ${input.score}/${input.total} (${overall}%) on the AI placement assessment, placing them at CEFR level **${level}**. Their strongest area is ${[...skills].sort((a, b) => b.pct - a.pct)[0]?.skill ?? 'grammar'} (${[...skills].sort((a, b) => b.pct - a.pct)[0]?.pct ?? 0}%); the area needing the most attention is ${[...skills].sort((a, b) => a.pct - b.pct)[0]?.skill ?? 'reading'} (${[...skills].sort((a, b) => a.pct - b.pct)[0]?.pct ?? 0}%).`;

  const competencies = skills.map((s) => ({
    skill: s.skill,
    label: SKILL_LABEL[s.skill].en,
    analysis:
      s.pct >= 80
        ? `Excellent control of ${SKILL_LABEL[s.skill].en} — answered ${s.correct} of ${s.total} correctly.`
        : s.pct >= 60
          ? `Solid working knowledge of ${SKILL_LABEL[s.skill].en} (${s.correct}/${s.total}). With targeted practice, this area can quickly become a strength.`
          : s.pct >= 40
            ? `${SKILL_LABEL[s.skill].en} is developing (${s.correct}/${s.total}). This is a high-leverage area for focused weekly practice.`
            : `${SKILL_LABEL[s.skill].en} needs the most attention right now (${s.correct}/${s.total}). Don't be discouraged — clear gaps make for fast progress with the right plan.`,
    recommendation:
      s.pct >= 80
        ? 'Maintain through occasional exam-style drills.'
        : s.pct >= 60
          ? 'Aim for 20 minutes of focused practice, 3× per week.'
          : 'Daily 30-minute focused sessions with weekly review at Rai.',
  }));

  return { summary, competencies };
}

async function aiNarrative(input: AnalysisInput, skills: SkillScore[]) {
  const key = process.env.DEEPSEEK_API_KEY;
  if (!key) return null;
  try {
    const prompt = `You are an experienced English teacher at Rai Language Center in Latakia. A student has just completed an AI-graded placement assessment.

Student: ${input.name}
CEFR level: ${input.level}
Overall score: ${input.score}/${input.total}

Per-skill breakdown:
${skills.map((s) => `- ${SKILL_LABEL[s.skill].en}: ${s.correct}/${s.total} (${s.pct}%)`).join('\n')}

Write:
1. A warm, specific 2-sentence summary addressing the student by name.
2. For each of the four competencies (Grammar, Vocabulary, Reading, Listening), a 2-sentence analysis and a 1-sentence specific practice recommendation.

Reply ONLY in JSON, no prose around it. Schema:
{
  "summary": "...",
  "competencies": [
    { "skill": "grammar",   "analysis": "...", "recommendation": "..." },
    { "skill": "vocab",     "analysis": "...", "recommendation": "..." },
    { "skill": "reading",   "analysis": "...", "recommendation": "..." },
    { "skill": "listening", "analysis": "...", "recommendation": "..." }
  ]
}`;

    const resp = await fetch('https://api.deepseek.com/chat/completions', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: 'You return strictly valid JSON. No prose.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.4,
        response_format: { type: 'json_object' },
        max_tokens: 900,
      }),
    });
    if (!resp.ok) {
      const t = await resp.text().catch(() => '');
      console.warn('[deepseek] non-200', resp.status, t);
      return null;
    }
    const json = (await resp.json()) as { choices?: { message?: { content?: string } }[] };
    const content = json.choices?.[0]?.message?.content ?? '';
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) return null;
    const parsed = JSON.parse(match[0]) as {
      summary: string;
      competencies: { skill: SkillTag; analysis: string; recommendation: string }[];
    };
    return {
      summary: parsed.summary,
      competencies: parsed.competencies.map((c) => ({
        skill: c.skill,
        label: SKILL_LABEL[c.skill].en,
        analysis: c.analysis,
        recommendation: c.recommendation,
      })),
    };
  } catch (err) {
    console.warn('[ai narrative] fell back to template:', err);
    return null;
  }
}

/* ============================================================================
   Public entry point
   ============================================================================ */

export async function generateAnalysis(input: AnalysisInput): Promise<AnalysisOutput> {
  const skills = computeSkillScores(input.answers);

  // Prefer AI; fall back to template
  const ai = await aiNarrative(input, skills);
  const narrative = ai ?? templateNarrative(input, skills);

  const recommendedCourse = recommendCourse(input.level, skills);
  const studyPlan = buildStudyPlan(input.level, skills);
  const radarSvg = radarChartSvg(skills, input.locale);

  return {
    level: input.level,
    score: input.score,
    total: input.total,
    skills,
    summary: narrative.summary,
    competencies: narrative.competencies,
    recommendedCourse,
    studyPlan,
    radarSvg,
  };
}
