/**
 * AI-graded English assessment analysis.
 *
 * Given a candidate's answers, computes a per-skill breakdown, picks a CEFR level,
 * generates a personalised study plan + course recommendation, and renders a radar
 * chart SVG of the four English competencies.
 *
 * If ANTHROPIC_API_KEY is set, the narrative analysis is generated by Claude.
 * Otherwise a deterministic template fills in. Either way, the chart + scores
 * are computed locally so the email always has consistent data.
 */

export type SkillTag = 'grammar' | 'reading' | 'speaking' | 'writing';

export type AnsweredQuestion = {
  questionId: string;
  selectedIndex: number;
  correct: boolean;
  skillTag?: string | null;
  difficulty?: number | null;
};

export type SkillScore = {
  skill: SkillTag;
  correct: number;
  total: number;
  pct: number; // 0–100
};

export type SpeechInput = {
  reference: string;   // the passage the student was asked to read
  transcript: string;  // what the browser's Web Speech API heard
};

export type WritingInput = {
  prompt: string;      // the writing task shown to the student
  text: string;        // their submitted paragraph
};

export type AnalysisInput = {
  name: string;
  email: string;
  locale: 'ar' | 'en';
  level: string; // A1..C2
  score: number;       // MCQ score
  total: number;       // MCQ total
  answers: AnsweredQuestion[];
  /** Optional Part-2: the read-aloud task transcript */
  speech?: SpeechInput;
  /** Optional Part-3: the written paragraph */
  writing?: WritingInput;
};

export type AnalysisOutput = {
  level: string;
  score: number;
  total: number;
  skills: SkillScore[];
  // Narrative pieces — used in email
  summary: string;
  competencies: { skill: SkillTag; label: string; analysis: string; recommendation: string }[];
  recommendedCourse: { id: string; title: string; why: string };
  studyPlan: { week: string; focus: string; activities: string[] }[];
  /** SVG markup of a 4-axis radar chart with the candidate's scores. */
  radarSvg: string;
  /** Raw artefacts for the admin's reference (transcript + written paragraph) */
  speechExcerpt?: { reference: string; transcript: string; accuracyPct: number };
  writingExcerpt?: { prompt: string; text: string; wordCount: number };
};

/* ============================================================================
   Skill score computation
   ============================================================================ */

const SKILL_LABEL: Record<SkillTag, { en: string; ar: string }> = {
  grammar:  { en: 'Grammar & Vocabulary', ar: 'القواعد والمفردات' },
  reading:  { en: 'Reading',              ar: 'القراءة' },
  speaking: { en: 'Speaking',             ar: 'المحادثة' },
  writing:  { en: 'Writing',              ar: 'الكتابة' },
};

const SKILLS: SkillTag[] = ['grammar', 'reading', 'speaking', 'writing'];

/**
 * Compute MCQ-derived skill scores. Maps the question's skill_tag to one of
 * 4 categories: grammar/vocab questions → grammar; reading questions →
 * reading; everything else → grammar (default).
 *
 * Speaking and writing scores come from a separate signal (transcript
 * accuracy + AI scoring) and are merged in computeFullSkillScores().
 */
export function computeMcqSkillScores(answers: AnsweredQuestion[]): { grammar: SkillScore; reading: SkillScore } {
  const grammar = answers.filter((a) => {
    const tag = a.skillTag ?? 'grammar';
    return tag === 'grammar' || tag === 'vocab' || tag === 'vocabulary';
  });
  const reading = answers.filter((a) => (a.skillTag ?? '') === 'reading');

  const score = (rows: AnsweredQuestion[], skill: SkillTag): SkillScore => {
    const correct = rows.filter((a) => a.correct).length;
    return {
      skill, correct, total: rows.length,
      pct: rows.length === 0 ? 0 : Math.round((correct / rows.length) * 100),
    };
  };

  return {
    grammar: score(grammar, 'grammar'),
    reading: score(reading, 'reading'),
  };
}

/**
 * Compute speech accuracy by simple word-level matching between the
 * reference passage and what the speech recognizer heard. Returns 0-100.
 */
export function computeSpeechAccuracy(reference: string, transcript: string): number {
  if (!transcript.trim()) return 0;
  const refWords = reference.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).filter(Boolean);
  const trWords  = transcript.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).filter(Boolean);
  if (refWords.length === 0) return 0;
  const trSet = new Set(trWords);
  const matched = refWords.filter((w) => trSet.has(w)).length;
  // Length penalty if the transcript is substantially shorter than the reference
  const lengthRatio = Math.min(1, trWords.length / Math.max(1, refWords.length));
  const raw = (matched / refWords.length) * lengthRatio;
  return Math.round(raw * 100);
}

/**
 * Heuristic baseline for writing quality before AI fills it in.
 * Word count, sentence count, lexical diversity → 0-100.
 */
export function computeWritingBaseline(text: string): { pct: number; wordCount: number; sentences: number; uniqueWords: number } {
  const words = text.trim().split(/\s+/).filter(Boolean);
  const sentences = text.split(/[.!?]+/).map((s) => s.trim()).filter(Boolean).length;
  const unique = new Set(words.map((w) => w.toLowerCase())).size;
  if (words.length < 10) return { pct: Math.round(words.length * 4), wordCount: words.length, sentences, uniqueWords: unique };
  const lengthScore = Math.min(40, Math.round((words.length / 80) * 40));      // up to 40 pts for ~80 words
  const sentenceScore = Math.min(20, sentences * 5);                            // up to 20 for ≥4 sentences
  const diversityScore = Math.min(40, Math.round((unique / Math.max(1, words.length)) * 40 * 1.5));
  return {
    pct: Math.min(100, lengthScore + sentenceScore + diversityScore),
    wordCount: words.length, sentences, uniqueWords: unique,
  };
}

/* ============================================================================
   Radar chart SVG
   ============================================================================ */

export function radarChartSvg(skills: SkillScore[], locale: 'ar' | 'en' = 'en'): string {
  const W = 560;
  const H = 460;
  const cx = W / 2;
  const cy = H / 2 + 10;
  const r = 150;
  const axes = SKILLS.length;
  // 4 axes: 0=top, 1=right, 2=bottom, 3=left
  const angle = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / axes;

  function point(idx: number, value01: number) {
    const rr = r * Math.max(0.04, value01);
    const a = angle(idx);
    return { x: cx + Math.cos(a) * rr, y: cy + Math.sin(a) * rr };
  }

  const grid = [0.25, 0.5, 0.75, 1].map((p) => {
    const pts = SKILLS.map((_, i) => point(i, p));
    return `<polygon points="${pts.map((pt) => `${pt.x.toFixed(1)},${pt.y.toFixed(1)}`).join(' ')}" fill="none" stroke="rgba(15,27,29,0.12)" stroke-width="1"/>`;
  }).join('');

  const axisLines = SKILLS.map((_, i) => {
    const end = point(i, 1);
    return `<line x1="${cx}" y1="${cy}" x2="${end.x.toFixed(1)}" y2="${end.y.toFixed(1)}" stroke="rgba(15,27,29,0.12)" stroke-width="1"/>`;
  }).join('');

  const labels = SKILLS.map((sk, i) => {
    const p = point(i, 1.18);
    return `<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" font-family="Georgia,'Times New Roman',serif" font-size="14" font-weight="600" fill="#0E5132" text-anchor="middle" dominant-baseline="middle">${SKILL_LABEL[sk][locale]}</text>`;
  }).join('');

  const valuePts = skills.map((s, i) => point(i, s.pct / 100));
  const valuePolygon = `<polygon points="${valuePts.map((pt) => `${pt.x.toFixed(1)},${pt.y.toFixed(1)}`).join(' ')}" fill="rgba(201,162,74,0.28)" stroke="#C9A24A" stroke-width="2.5"/>`;
  const valueDots = valuePts
    .map((pt) => `<circle cx="${pt.x.toFixed(1)}" cy="${pt.y.toFixed(1)}" r="4.5" fill="#0E5132" stroke="#C9A24A" stroke-width="1.5"/>`)
    .join('');

  const pctLabels = skills
    .map((s, i) => {
      const p = point(i, Math.max(0.18, s.pct / 100 + 0.06));
      return `<text x="${p.x.toFixed(1)}" y="${p.y.toFixed(1)}" font-family="Georgia,serif" font-size="11" fill="#0F1B1D" text-anchor="middle" dominant-baseline="middle">${s.pct}%</text>`;
    })
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <rect width="100%" height="100%" fill="#FBF8F2"/>
  ${grid}
  ${axisLines}
  ${valuePolygon}
  ${valueDots}
  ${labels}
  ${pctLabels}
</svg>`;
}

/* ============================================================================
   Course recommendation (deterministic, level + skill aware)
   ============================================================================ */

function recommendCourse(level: string, skills: SkillScore[]): AnalysisOutput['recommendedCourse'] {
  const weak = [...skills].sort((a, b) => a.pct - b.pct)[0];
  if (level === 'A1' || level === 'A2') {
    return {
      id: 'adults',
      title: 'Adult Conversation (Foundation track)',
      why: `At ${level}, the priority is building a confident foundation in everyday English. Our small-group Foundation track focuses on the four skills together, with extra ${weak.skill} work where needed.`,
    };
  }
  if (level === 'B1' || level === 'B2') {
    if (weak.skill === 'reading' || weak.skill === 'grammar') {
      return {
        id: 'exams',
        title: 'TOEFL & IELTS Prep',
        why: `At ${level}, you have the range to start exam prep. Our TOEFL/IELTS track will sharpen your ${weak.skill} (your current weakest area) while you build the test-taking strategies that turn intermediate English into a band 6.5+ or TOEFL 80+.`,
      };
    }
    return {
      id: 'business',
      title: 'Business English',
      why: `At ${level} you are ready for workplace English. The Business track focuses on professional speaking, writing, and presentations — using your strengths to fast-track confident communication.`,
    };
  }
  // C1/C2
  return {
    id: 'private',
    title: 'Private 1-on-1 (Advanced)',
    why: `At ${level}, group classes won't stretch you. A dedicated tutor will target the specific edges of your English — nuance, register, idiom — and prepare you for the demands of native-level work.`,
  };
}

/* ============================================================================
   Study plan
   ============================================================================ */

function buildStudyPlan(level: string, skills: SkillScore[]): AnalysisOutput['studyPlan'] {
  const weak = [...skills].sort((a, b) => a.pct - b.pct);
  const w1 = weak[0]?.skill ?? 'grammar';
  const w2 = weak[1]?.skill ?? 'vocab';

  return [
    {
      week: 'Weeks 1–2 · Diagnostic & Foundation',
      focus: `Stabilise your ${SKILL_LABEL[w1].en} as your priority skill`,
      activities: [
        `30 min/day targeted ${SKILL_LABEL[w1].en} drills`,
        '15 min/day listening (BBC Learning English or VOA Learning English)',
        'Weekly 1-hour conversation circle at Rai',
      ],
    },
    {
      week: 'Weeks 3–6 · Range',
      focus: `Add depth in ${SKILL_LABEL[w2].en} while consolidating week 1–2 gains`,
      activities: [
        'Read one news article per day (Reuters, Al Jazeera English)',
        'Write a short journal entry (5 sentences) every other day',
        'Bi-weekly mock test at Rai with feedback',
      ],
    },
    {
      week: 'Weeks 7–10 · Speaking & Confidence',
      focus: 'Convert understanding into spoken fluency',
      activities: [
        'Two conversation sessions per week (group or 1-on-1)',
        'Watch one English film with English subtitles each week',
        'Record yourself summarising an article for 1 minute',
      ],
    },
    {
      week: 'Weeks 11–12 · Reassessment',
      focus: 'Re-take the assessment and target the next level up',
      activities: [
        'Full mock exam at Rai',
        'Set goals for the next 3 months with your Rai instructor',
        'Decide on follow-on course (exam prep, business, or private)',
      ],
    },
  ];
}

/* ============================================================================
   Narrative analysis — DeepSeek (OpenAI-compatible) w/ template fallback
   ============================================================================ */

function templateNarrative(input: AnalysisInput, skills: SkillScore[]) {
  const strongest = [...skills].sort((a, b) => b.pct - a.pct)[0];
  const weakest = [...skills].sort((a, b) => a.pct - b.pct)[0];
  const summary = `${input.name}, you completed all three parts of the assessment. Your strongest area is ${SKILL_LABEL[strongest.skill].en} (${strongest.pct}%); your highest-leverage growth area is ${SKILL_LABEL[weakest.skill].en} (${weakest.pct}%).`;

  const competencies = skills.map((s) => {
    const label = SKILL_LABEL[s.skill].en;
    const tier =
      s.pct >= 80 ? 'excellent' :
      s.pct >= 60 ? 'solid' :
      s.pct >= 40 ? 'developing' :
      'beginning';
    const analysisMap: Record<string, string> = {
      excellent: `Excellent control of ${label}. The evidence shows confident, accurate performance.`,
      solid:     `Solid working knowledge of ${label}. With targeted practice this becomes a strength.`,
      developing:`${label} is developing. This is a high-leverage area for focused weekly practice.`,
      beginning: `${label} needs the most attention right now. Don't be discouraged — clear gaps mean fast progress with the right plan.`,
    };
    const recMap: Record<string, string> = {
      excellent: 'Maintain through occasional exam-style drills.',
      solid:     'Aim for 20 minutes of focused practice, 3× per week.',
      developing:'Daily 30-minute focused sessions with weekly review at Rai.',
      beginning: 'Start with foundational drills 5× per week with a Rai instructor.',
    };
    return {
      skill: s.skill,
      label,
      pct: s.pct,
      analysis: analysisMap[tier],
      recommendation: recMap[tier],
    };
  });

  return { summary, competencies, overallLevel: input.level as string };
}

async function aiNarrative(input: AnalysisInput, skills: SkillScore[]) {
  const key = process.env.DEEPSEEK_API_KEY;
  if (!key) return null;
  try {
    const speechBlock = input.speech
      ? `\n\nPART 2 — READ-ALOUD TASK\nReference passage shown to the student:\n"${input.speech.reference}"\n\nWhat the speech recognizer captured the student saying:\n"${input.speech.transcript || '(silent / no recording)'}"\n`
      : '';

    const writingBlock = input.writing
      ? `\n\nPART 3 — WRITING TASK\nPrompt: ${input.writing.prompt}\nStudent's submission:\n"""\n${input.writing.text || '(left blank)'}\n"""\n`
      : '';

    const prompt = `You are a senior English teacher at Rai Language Center in Latakia, evaluating a placement assessment with THREE parts. Score each of FOUR competencies (Grammar & Vocabulary, Reading, Speaking, Writing) based on the evidence below.

Student: ${input.name}
Provisional CEFR (from MCQ): ${input.level}

PART 1 — 25 MULTIPLE-CHOICE QUESTIONS
Per-skill MCQ breakdown:
${skills.map((s) => `- ${SKILL_LABEL[s.skill].en}: ${s.correct}/${s.total} (${s.pct}%)`).join('\n')}${speechBlock}${writingBlock}

For the Speaking competency, judge by how well the transcript matches the reference passage AND fluency cues in the transcript (missing words, repeated words, partial phrases).

For the Writing competency, judge as a professional English teacher: grammar correctness, vocabulary range, sentence variety, coherence, task achievement. Be specific — quote one sentence the student wrote if useful.

Return a detailed JSON report, strictly this schema, no prose around it:
{
  "summary": "2-3 sentence warm summary addressing the student by name. Cite one strong area and one growth area.",
  "competencies": [
    { "skill": "grammar",  "pct": 0-100, "analysis": "3-4 specific sentences citing evidence", "recommendation": "1 actionable sentence" },
    { "skill": "reading",  "pct": 0-100, "analysis": "3-4 specific sentences", "recommendation": "1 actionable sentence" },
    { "skill": "speaking", "pct": 0-100, "analysis": "3-4 specific sentences citing what they said vs. the reference", "recommendation": "1 actionable sentence" },
    { "skill": "writing",  "pct": 0-100, "analysis": "3-4 specific sentences citing the student's actual writing", "recommendation": "1 actionable sentence" }
  ],
  "overallLevel": "A1|A2|B1|B2|C1|C2"
}`;

    const resp = await fetch('https://api.deepseek.com/chat/completions', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: 'You are an experienced senior English teacher. You return strictly valid JSON matching the user\'s schema, no prose around it.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.5,
        response_format: { type: 'json_object' },
        max_tokens: 2000,
      }),
    });
    if (!resp.ok) {
      const t = await resp.text().catch(() => '');
      console.warn('[deepseek] non-200', resp.status, t);
      return null;
    }
    const json = (await resp.json()) as { choices?: { message?: { content?: string } }[] };
    const content = json.choices?.[0]?.message?.content ?? '';
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) return null;
    const parsed = JSON.parse(match[0]) as {
      summary: string;
      competencies: { skill: SkillTag; pct?: number; analysis: string; recommendation: string }[];
      overallLevel?: string;
    };
    return {
      summary: parsed.summary,
      overallLevel: parsed.overallLevel,
      competencies: parsed.competencies.map((c) => ({
        skill: c.skill,
        label: SKILL_LABEL[c.skill]?.en ?? c.skill,
        pct: typeof c.pct === 'number' ? Math.max(0, Math.min(100, c.pct)) : undefined,
        analysis: c.analysis,
        recommendation: c.recommendation,
      })),
    };
  } catch (err) {
    console.warn('[ai narrative] fell back to template:', err);
    return null;
  }
}

/* ============================================================================
   Public entry point
   ============================================================================ */

export async function generateAnalysis(input: AnalysisInput): Promise<AnalysisOutput> {
  // 1) Local signals
  const mcq = computeMcqSkillScores(input.answers);
  const speechAcc = input.speech ? computeSpeechAccuracy(input.speech.reference, input.speech.transcript) : 0;
  const writingBaseline = input.writing ? computeWritingBaseline(input.writing.text) : { pct: 0, wordCount: 0, sentences: 0, uniqueWords: 0 };

  // 2) Build the four-skill scores (use AI's pct override below if it returned one)
  const baseSkills: SkillScore[] = [
    { skill: 'grammar',  correct: mcq.grammar.correct, total: mcq.grammar.total, pct: mcq.grammar.pct },
    { skill: 'reading',  correct: mcq.reading.correct, total: mcq.reading.total, pct: mcq.reading.pct },
    { skill: 'speaking', correct: 0, total: 0, pct: speechAcc },
    { skill: 'writing',  correct: 0, total: 0, pct: writingBaseline.pct },
  ];

  // 3) AI narrative (or template fallback)
  const ai = await aiNarrative(input, baseSkills);
  const narrative = ai ?? templateNarrative(input, baseSkills);

  // 4) If AI gave a per-skill pct, use it (more nuanced than our heuristics)
  const skills: SkillScore[] = baseSkills.map((s) => {
    const fromAi = narrative.competencies?.find((c) => c.skill === s.skill && typeof (c as { pct?: number }).pct === 'number');
    if (fromAi && typeof (fromAi as { pct?: number }).pct === 'number') {
      return { ...s, pct: (fromAi as { pct: number }).pct };
    }
    return s;
  });

  // 5) Recompute overall level from the 4-skill average if AI gave us a level
  const overall = ai?.overallLevel || input.level;
  const overallPct = Math.round(skills.reduce((a, s) => a + s.pct, 0) / skills.length);

  const recommendedCourse = recommendCourse(overall, skills);
  const studyPlan = buildStudyPlan(overall, skills);
  const radarSvg = radarChartSvg(skills, input.locale);

  return {
    level: overall,
    score: overallPct,
    total: 100,
    skills,
    summary: narrative.summary,
    competencies: narrative.competencies.map((c) => ({
      skill: c.skill, label: c.label, analysis: c.analysis, recommendation: c.recommendation,
    })),
    recommendedCourse,
    studyPlan,
    radarSvg,
    speechExcerpt: input.speech ? {
      reference: input.speech.reference,
      transcript: input.speech.transcript,
      accuracyPct: speechAcc,
    } : undefined,
    writingExcerpt: input.writing ? {
      prompt: input.writing.prompt,
      text: input.writing.text,
      wordCount: writingBaseline.wordCount,
    } : undefined,
  };
}
